message(STATUS "${BoldBlue}───────────────────────────────────────────────${ColourReset}")
message(STATUS "${Blue}[ARCH                   ]${ColourReset}: ${ARCH}")
message(STATUS "${Blue}[PLATFORM               ]${ColourReset}: ${PLATFORM}")
message(STATUS "${Blue}[CMAKE_BUILD_TYPE       ]${ColourReset}: ${CMAKE_BUILD_TYPE}")
message(STATUS "${Blue}[APP_NAME               ]${ColourReset}: ${APP_NAME}")
message(STATUS "${Blue}[PKG_NAME               ]${ColourReset}: ${PKG_NAME}")
message(STATUS "${Blue}[VERSION                ]${ColourReset}: ${VERSION}")
message(STATUS "${Blue}[DESCRIPTION            ]${ColourReset}: ${DESCRIPTION}")
message(STATUS "${Blue}[APP_ROOT_DIR           ]${ColourReset}: ${APP_ROOT_DIR}")
message(STATUS "${Blue}[BUILD_DATE             ]${ColourReset}: ${BUILD_DATE}")
message(STATUS "${Blue}[GIT_HASH               ]${ColourReset}: ${GIT_HASH}")
message(STATUS "${Blue}[CMAKE_CXX_FLAGS        ]${ColourReset}: ${CMAKE_CXX_FLAGS}")
if(${CMAKE_BUILD_TYPE} STREQUAL "Release")
    message(STATUS "${Blue}[CMAKE_CXX_FLAGS_RELEASE]${ColourReset}: ${CMAKE_CXX_FLAGS_RELEASE}")
else()
    message(STATUS "${Blue}[CMAKE_CXX_FLAGS_DEBUG  ]${ColourReset}: ${CMAKE_CXX_FLAGS_DEBUG}")
endif()
message(STATUS "${BoldBlue}───────────────────────────────────────────────${ColourReset}")